version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api

  api:
    build: ./projects/api
    depends_on:
      - postgres
      - redis
    environment:
      # These env variables are necessary to let Nginx reverse proxy us.
      - VIRTUAL_HOST=api.margaret.com
      - VIRTUAL_PORT=8080

      # These env variables will be read from the host machine.
      - MIX_ENV

  web:
    build: ./projects/web
    environment:
      # These env variables are necessary to let Nginx reverse proxy us.
      - VIRTUAL_HOST=margaret.com
      - VIRTUAL_PORT=80

      # These env variables will be read from the host machine.
      - NODE_ENV
  
  ml:
    build: ./projects/ml


  postgres:
    image: postgres:10.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:4.0.6
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
