apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: margaret
    pod: api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: margaret
    pod: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: margaret
      pod: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: mrgaret/api:latest